# -*- coding: utf-8 -*-
"""AI(knn).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kx3IoNowbUsKke6-AlaJF7ubhJRFRnxw
"""

from google.colab import files

uploaded = files.upload()  # Opens a file dialog to upload CSV

import pandas as pd
import pickle  # For saving model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier

# Load dataset
df = pd.read_csv("job_salaries_dataset.csv")

# Encode categorical variables
label_encoders = {}
categorical_columns = ["Job Title", "Education Level", "Industry", "Company Size", "Location Type"]

for col in categorical_columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

# Prepare data
X = df.drop(columns=["Salary Category"])
y_raw = df["Salary Category"]

salary_encoder = LabelEncoder()
y = salary_encoder.fit_transform(y_raw)

# Standardize numerical features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train k-NN model
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# ✅ Save the trained model & preprocessors using pickle
with open("knn_model.pkl", "wb") as f:
    pickle.dump(knn, f)

with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

with open("salary_encoder.pkl", "wb") as f:
    pickle.dump(salary_encoder, f)

with open("label_encoders.pkl", "wb") as f:
    pickle.dump(label_encoders, f)

print("✅ Model trained and saved successfully using pickle!")